name: Demo Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

  push:
    branches: [main, develop]
    paths:
      - 'demo/**'
      - 'src/**'
      - 'assets/**'
      - 'index.html'
      - 'style.css'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build demo
        run: yarn demo:build

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push if changed
        run: |
          git add demo/dist -f
          git diff --staged --quiet || (git commit -m "chore: update demo build [skip ci]" && git push) 
