name: Publish Package and Create Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Generate docs
              run: yarn docs

            - name: Build demo
              run: yarn demo:build

            - name: List files for release
              run: |
                echo "=== Package files ==="
                ls -la dist/
                echo "=== Demo files ==="
                ls -la demo/dist/
                echo "=== Docs files ==="
                ls -la demo/public/docs/

            - name: Publish to NPM
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                    dist/index.js
                    dist/index.d.ts
                    dist/index.esm.js
                    dist/index.esm.js.map
                    dist/index.js.map
                    demo/dist/index.html
                    demo/dist/assets/**
                    demo/public/docs/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy documentation
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
